<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Runtime configuration, loaded from config/config.php (written by install.php).
 */
final class Config
{
    private static array $data = [];
    private static bool $loaded = false;

    public static function path(): string
    {
        return dirname(__DIR__, 2) . '/config/config.php';
    }

    public static function exists(): bool
    {
        return is_file(self::path());
    }

    public static function load(bool $force = false): void
    {
        if (self::$loaded && !$force) {
            return;
        }
        self::$data = self::exists() ? (require self::path()) : [];
        self::$loaded = true;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        self::load();
        $value = self::$data;
        foreach (explode('.', $key) as $segment) {
            if (!is_array($value) || !array_key_exists($segment, $value)) {
                return $default;
            }
            $value = $value[$segment];
        }
        return $value;
    }

    public static function all(): array
    {
        self::load();
        return self::$data;
    }

    /**
     * Write config/config.php atomically. Re-installing overwrites it in place.
     */
    public static function write(array $data): void
    {
        $export = var_export($data, true);
        $php = "<?php\n\n/**\n * Generated by install.php on " . date('Y-m-d H:i:s')
             . ".\n * Editing by hand is fine; re-running the installer overwrites it.\n */\n\nreturn "
             . $export . ";\n";

        $target = self::path();
        $tmp = $target . '.' . bin2hex(random_bytes(4)) . '.tmp';
        if (file_put_contents($tmp, $php, LOCK_EX) === false) {
            throw new \RuntimeException('เขียนไฟล์ config ไม่สำเร็จ: ' . $tmp);
        }
        if (!@rename($tmp, $target)) {
            @unlink($tmp);
            throw new \RuntimeException('ย้ายไฟล์ config ไม่สำเร็จ: ' . $target);
        }
        @chmod($target, 0640);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($target, true);
        }
        self::load(true);
    }
}
